### ISSUE TITLE
Investigate internal error

### ISSUE THREAD

**Issue by niknetniko** [dodona-edu/universal-judge#465]
Stderr:
```
Pylint crashed with
Traceback (most recent call last):
  File "/mnt/X7G8DMYVScTX-2wZKYyjFA/judge/tested/languages/python/linter.py", line 46, in run_pylint
    lint.Run(args, reporter=JSONReporter(output=pylint_out), do_exit=False)
TypeError: Run.__init__() got an unexpected keyword argument 'do_exit'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/mnt/X7G8DMYVScTX-2wZKYyjFA/judge/tested/__main__.py", line 45, in <module>
    run(configuration, out)
  File "/mnt/X7G8DMYVScTX-2wZKYyjFA/judge/tested/main.py", line 38, in run
    judge(pack)
  File "/mnt/X7G8DMYVScTX-2wZKYyjFA/judge/tested/judge/core.py", line 187, in judge
    result_status, currently_open_tab = _process_results(
                                        ^^^^^^^^^^^^^^^^^
  File "/mnt/X7G8DMYVScTX-2wZKYyjFA/judge/tested/judge/core.py", line 325, in _process_results
    continue_ = evaluate_context_results(
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/X7G8DMYVScTX-2wZKYyjFA/judge/tested/judge/evaluation.py", line 296, in evaluate_context_results
    missing_stdout = _evaluate_channel(
                     ^^^^^^^^^^^^^^^^^^
  File "/mnt/X7G8DMYVScTX-2wZKYyjFA/judge/tested/judge/evaluation.py", line 113, in _evaluate_channel
    evaluation_result = evaluator(output, actual if actual else "")
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/X7G8DMYVScTX-2wZKYyjFA/judge/tested/oracles/programmed.py", line 54, in evaluate
    result = evaluate_programmed(
             ^^^^^^^^^^^^^^^^^^^^
  File "/mnt/X7G8DMYVScTX-2wZKYyjFA/judge/tested/judge/programmed.py", line 45, in evaluate_programmed
    return _evaluate_python(bundle, evaluator, expected, actual)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/X7G8DMYVScTX-2wZKYyjFA/judge/tested/judge/programmed.py", line 221, in _evaluate_python
    exec(f"__tested_test__result = {literal_function_call}", global_env)
  File "<string>", line 1, in <module>
  File "<string>", line 23, in evaluate_value
IndexError: string index out of range
```

Ignore the pylint stuff, see #463 for that.

**Comment by niknetniko** [comment]
This is an issue with the custom oracle, not much we can do about this.
